"""
Report Generator
==================
Produces Markdown reports (rendered to PDF via WeasyPrint in production —
see requirements.txt) for three audiences: executive summary, technical/
developer detail, and a migration checklist. Markdown-first means the same
content can be emailed, rendered in-app, or exported without duplicating
templates per format.
"""
from __future__ import annotations

from datetime import datetime

from app.models.schemas import ScanSummary


def generate_executive_report(scan: ScanSummary) -> str:
    s = scan.scores
    md = f"""# QuantumShield AI — Executive Security & Quantum Readiness Report

**Target:** {scan.target_name}
**Scan Date:** {scan.completed_at.strftime('%B %d, %Y')}
**Files Analyzed:** {scan.files_scanned}

## Headline Scores

| Metric | Score | Grade |
|---|---|---|
| Overall Security Health | {s.overall_health}/100 | {s.grade} |
| Security Score (current threats) | {s.security_score}/100 | |
| Quantum Readiness Score | {s.quantum_readiness_score}/100 | |
| Compliance Score | {s.compliance_score}/100 | |
| Risk Trend | {s.risk_trend} | |

## Summary

This scan identified **{scan.total_findings} findings** across {scan.files_scanned} files.
{scan.findings_by_severity.get('critical', 0)} are rated Critical and require immediate action.

## Business Risk Framing

- **Today's risk:** Findings in authentication, secrets management, and legacy cryptography
  represent immediate exploitable attack surface.
- **Tomorrow's risk:** Quantum-vulnerable cryptography (RSA/ECC/Diffie-Hellman) does not need
  a working quantum computer to matter today — adversaries can harvest encrypted traffic now
  and decrypt it retroactively once cryptographically relevant quantum computers exist
  ("harvest now, decrypt later"). This is especially material for data with long confidentiality
  lifetimes: health records, government/defense communications, financial records, IP.

## Recommended Next Steps

1. Remediate all Critical findings within 30 days.
2. Begin cryptographic inventory (CBOM) validation against this report.
3. Prioritize PQC migration for systems protecting long-lived sensitive data.
4. Re-scan on a recurring cadence (CI/CD integration) to track the Risk Trend metric.

---
*Generated by QuantumShield AI. This report is a static-analysis-based assessment and does not
replace a full penetration test or formal compliance audit.*
"""
    return md


def generate_technical_report(scan: ScanSummary) -> str:
    lines = [f"# QuantumShield AI — Technical Findings Report\n", f"**Target:** {scan.target_name}\n"]
    by_cat: dict[str, list] = {}
    for f in scan.findings:
        by_cat.setdefault(f.category.value, []).append(f)

    for cat, findings in by_cat.items():
        lines.append(f"\n## {cat.replace('_', ' ').title()} ({len(findings)} findings)\n")
        for f in findings:
            lines.append(f"### [{f.severity.value.upper()}] {f.title}")
            lines.append(f"- **File:** `{f.file_path}:{f.line_number}`")
            lines.append(f"- **Rule:** {f.matched_pattern}  |  **CWE:** {f.cwe_id or 'N/A'}")
            if f.code_snippet:
                lines.append(f"- **Snippet:** `{f.code_snippet}`")
            lines.append(f"- **Description:** {f.description}")
            lines.append(f"- **Remediation:** {f.remediation}")
            if f.nist_pqc_recommendation:
                lines.append(f"- **PQC Recommendation:** {f.nist_pqc_recommendation}")
            lines.append("")
    return "\n".join(lines)


def generate_migration_checklist(scan: ScanSummary) -> str:
    quantum = [f for f in scan.findings if f.category.value == "quantum_vulnerable_crypto"]
    lines = [f"# Post-Quantum Migration Checklist — {scan.target_name}\n"]
    if not quantum:
        lines.append("No quantum-vulnerable cryptography detected in this scan. ✅")
        return "\n".join(lines)

    lines.append(f"{len(quantum)} quantum-vulnerable crypto usages found. Checklist:\n")
    for f in quantum:
        harvest = " ⚠️ HARVEST-NOW-DECRYPT-LATER RISK" if f.quantum_harvest_now_risk else ""
        lines.append(f"- [ ] `{f.file_path}:{f.line_number}` — {f.title}{harvest}")
        lines.append(f"      → Migrate to: {f.nist_pqc_recommendation}")
    return "\n".join(lines)
